### PR TITLE
Cleaned up theme references.

### PR DESCRIPTION
**Pull request by Jos512**
Going through the theme I found some references to another Feliciano project. Removed those or replaced them with those for the Hugo newsletter.

No problem if I've been to aggressive with cleaning up.

### CODE REVIEW

**Comment by Jos512** [comment]
With the latest commits above I also cleaned up some other resources that weren't used by the theme: Shopify (from another project), jQuery, and FontAwesome.

With this action I did assume that the final theme will not become so complex or 'creative' that we need those heavy libraries. 

(But that's of course depending on which direction you want to go, it's more like a suggestion from my part to not include those big libraries that are a drag on pagespeed.)

**Comment by felicianotech** [comment]
Hi,

So the reason for this is that I forked another Hugo website I have to create this one. I'm going through this PR now. I do know that I want to keep jQuery and FontAwesome because I will be using those soon when I start working on building out this website.

**Comment by felicianotech** [comment]
So I'm going to close this PR. There's a lot that I want deleted, but there's several things I want to keep as well. Thank you for the PR though.

**Comment by Jos512** [comment]
Fair enough, no problem.

> There's a lot that I want deleted, but there's several things I want to keep as well. 

Do you want smaller pull requests in the future, even if that means splitting up a topic ('clean up theme references') in multiple separate pull requests?

Have a nice weekend. 🙂

**Comment by felicianotech** [comment]
Smaller PRs are always better. In the next few weeks I'll start working on this much more, and opening Issues that target specific things we need to do. Typically, a PR per Issue works well.

**Comment by Jos512** [comment]
> Typically, a PR per Issue works well.

Would you rather have me create pull requests based on open issues, instead of coming up with pull requests on my own?

> In the next few weeks I'll start working on this much more, and opening Issues that target specific things we need to do.

In the *next weeks*? Oh boy I already feel this process goes slow. 😄 Can't imagine having to wait two weeks for a to do list to appear. 😉 

(Whichever speed you take is fine of course, since it's your project. Just sharing how I look at it.)

**Pull request closed without merging**
